# Generated by Django 6.0.1 on 2026-01-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('summary', models.TextField()),
                ('isbn', models.CharField(max_length=13)),
                ('genre', models.ManyToManyField(to='bookshelf.genre')),
            ],
        ),
    ]
