# Generated by Django 6.0.1 on 2026-01-27 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='bookshelf.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Administered'), ('t', 'Taken'), ('a', 'Available'), ('r', 'Reserved')], default='d', max_length=1, verbose_name='Status'),
        ),
    ]
